// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulationManager.Infrastructure.Persistence;

#nullable disable

namespace SimulationManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511135724_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SimulationManager.Domain.Entities.FuelComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Composition")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("composition");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Composition"), "utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_fuel_compositions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_fuel_compositions_user_id");

                    b.ToTable("fuel_compositions");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FuelCompositionId")
                        .HasColumnType("int")
                        .HasColumnName("fuel_composition_id");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("parameters");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_simulations");

                    b.HasIndex("FuelCompositionId")
                        .HasDatabaseName("i_x_simulations_fuel_composition_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_simulations_user_id");

                    b.ToTable("simulations");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.SimulationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ResultJson")
                        .HasColumnType("json")
                        .HasColumnName("result_json");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ResultJson"), "utf8mb4");

                    b.Property<int>("SimulationId")
                        .HasColumnType("int")
                        .HasColumnName("simulation_id");

                    b.HasKey("Id")
                        .HasName("p_k_simulation_results");

                    b.HasIndex("SimulationId")
                        .IsUnique()
                        .HasDatabaseName("i_x_simulation_results_simulation_id");

                    b.ToTable("simulation_results");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.FuelComposition", b =>
                {
                    b.HasOne("SimulationManager.Domain.Entities.User", "User")
                        .WithMany("FuelCompositions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_fuel_compositions__users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.Simulation", b =>
                {
                    b.HasOne("SimulationManager.Domain.Entities.FuelComposition", "FuelComposition")
                        .WithMany("Simulations")
                        .HasForeignKey("FuelCompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_simulations_fuel_compositions_fuel_composition_id");

                    b.HasOne("SimulationManager.Domain.Entities.User", "User")
                        .WithMany("Simulations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_simulations__users_user_id");

                    b.Navigation("FuelComposition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.SimulationResult", b =>
                {
                    b.HasOne("SimulationManager.Domain.Entities.Simulation", "Simulation")
                        .WithOne("SimulationResult")
                        .HasForeignKey("SimulationManager.Domain.Entities.SimulationResult", "SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_simulation_results_simulations_simulation_id");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.FuelComposition", b =>
                {
                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.Simulation", b =>
                {
                    b.Navigation("SimulationResult");
                });

            modelBuilder.Entity("SimulationManager.Domain.Entities.User", b =>
                {
                    b.Navigation("FuelCompositions");

                    b.Navigation("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
